### ISSUE TITLE
wine-staging?

### ISSUE THREAD

**Issue by mkljczk** [laino/wine-patches#1]
Hi. Thanks for your work on WINE, these patches are great. I wonder why it's not (yet) in wine-staging. Having performance-related things like this would make more people want to use WINE. I don't think that it would cause any problems. :)

**Comment by laino** [comment]
Spent some time trying to convince the relevant people of the merit of the patches, but was met by a wall of "Meh." and what seemed like a dislike of having random & unknown people suddenly submit patches that change some fundamentals (like the heap stuff).

**Comment by laino** [comment]
On second thought let's leave this open until it makes its way into wine-staging one way or another.

**Comment by mkljczk** [comment]
Meh, I thought that now, after changing name to wine-staging, it isn't place just for compholio's patches, but I see that I was wrong…

**Comment by mkljczk** [comment]
@laino, what about sending it there: https://dev.wine-staging.com/patches/submit/ ?
