### ISSUE TITLE
Please, send this patch to wine-staging

### ISSUE THREAD

**Issue by mkljczk** [laino/wine-patches#2]
DarkPlayer (wine-staging developer) said on IRC that your patches hadn't 
been sent to wine-staging. It seems that there is chance to make them 
included in next wine-staging. What about sending them there?
Logs from IRC:
17:21:40 <+ DarkPlayer> Regarding laino's patches: Nobody has tried to 
submit them to wine staging as far as i know.
20:04:53 <+ DarkPlayer> m4sk1n: i took a first glance on the patches and 
most of them are related to the memory management of wine. Making 
changes there is difficult because there are a lot of buggy applications 
with user after free errors which only work on windows, because the page 
was not reused / reclaimed yet.
20:07:16 <+ DarkPlayer> m4sk1n: but after all, wine staging is there to 
test the impact of these changes, so i guess his chances are higher if 
he tries to submit them to wine staging first

**Comment by mkljczk** [comment]
I have sent this patches on dev.wine-staging.com, hope that one day they'll be included in wine-staging

**Comment by tr37ion** [comment]
@laino Your patches would be a nice addition to next Wine Staging version. 

Though, there seem to be some open questions regarding your patches. Could you please get in contact with Wine Staging devs on irc://chat.freenote.net/wine-staging and by joining [Dev](https://dev.wine-staging.com) website? I guess, there are only some basic questions on how to implement those patches in Wine Staging.

@m4sk1n already committed your patches for Staging review [here](https://dev.wine-staging.com/profiles/26).

If you are busy, please let us know. Thanks in advance.
